# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    #Install chrome
    - name: Install chrome, package and run test
      run: |
        sudo apt-get update 
        sudo apt-get install google-chrome-stable
    #Install package in package.json
    - name: Install Package 
      run: npm install
    #Run test
    - name: Run test 
      run: npm run test
    #Using actions that published in Marketplace
    - name: Hello world action step
      id: hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: $JOHN1
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    # Use action-a folder
    - name: Install @actions/core and @actions/github
      run: npm install @actions/core @actions/github
    - name: Get the name in action folder
      id: john
      uses: ./.github/actions/action-a
      with:
        who-to-greet: 'Anna'
        time: '${{steps.outputs.hello.time}}'
    # Trigger another repository
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{secrets.MLEM}}
        repository: vuhuykhanh/sample-github-action-2
        event-type: my-event
env: 
  JOHN: JohnCena
